"""
backend/models/user.py
──────────────────────
SQLAlchemy 2.0 ORM model for the users table.

Sprint 1 — one table only.
Sprint 2 — added aws_account relationship.

Design decisions:
  - UUID primary key: prevents enumerable IDs in API responses and URLs.
  - email stored lowercase: normalised at the repository layer before insert/query.
  - password_hash: NEVER stores plain text — bcrypt hash only.
  - timezone-aware timestamps: always UTC, never naive datetimes.
  - Named indexes: explicit names make migrations readable and reversible.
  - server_default on is_active: PostgreSQL enforces the default even for
    raw INSERT statements that bypass SQLAlchemy.
"""

import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, Index, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.core.database import Base
if TYPE_CHECKING:
    from backend.models.aws_account import AWSAccount
    from backend.models.bucket import Bucket
    from backend.models.shared_link import SharedLink


class User(Base):
    """
    Represents a registered CloudVault user.

    Relationships:
      - aws_account   : One user -> at most one AWS account connection (1:1, Sprint 2)
      - buckets       : One user -> many managed S3 buckets (Sprint 3+)
      - activity_logs : One user -> many action records (Sprint 4+)
    """

    __tablename__ = "users"

    # ── Primary Key ───────────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        comment="UUID v4 — unique user identifier",
    )

    # ── Identity ──────────────────────────────────────────────────────────────
    full_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="User's display name (2–255 characters)",
    )
    email: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        unique=True,
        comment="Unique lowercase email — used as login identifier",
    )

    # ── Security ──────────────────────────────────────────────────────────────
    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="bcrypt hash — NEVER store plain-text password here",
    )

    # ── Status ────────────────────────────────────────────────────────────────
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",   # PostgreSQL-level default for raw INSERTs
        comment="False = account suspended; active users can log in",
    )
    is_admin: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        comment="True if user is a system administrator",
    )

    # ── Timestamps (UTC) ──────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        comment="Account creation timestamp (UTC)",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        comment="Last modification timestamp — auto-updated on every UPDATE",
    )

    # ── Relationships (Sprint 2+) ─────────────────────────────────────────────
    # uselist=False makes this a 1:1 — each user has at most one AWSAccount row.
    # cascade="all, delete-orphan" — deleting a User also deletes their AWSAccount.
    aws_account: Mapped["AWSAccount"] = relationship(  
        "AWSAccount",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )

    # Sprint 3: One User → many Bucket records (local metadata only).
    # Deleting a user removes their CloudVault bucket records (NOT the actual S3 buckets).
    buckets: Mapped[list["Bucket"]] = relationship(  
        "Bucket",
        back_populates="user",
        cascade="all, delete-orphan",
    )
    # Sprint 8: Active S3 shared links generated by this user
    shared_links: Mapped[list["SharedLink"]] = relationship( 
        "SharedLink",
        back_populates="user",
        cascade="all, delete-orphan",
    )

    # ── Database Indexes ──────────────────────────────────────────────────────
    # Named indexes allow Alembic to generate clean up/downgrade statements.
    __table_args__ = (
        Index("ix_users_email", "email"),          # Fast lookup during login
        Index("ix_users_is_active", "is_active"),  # Filter active users
    )

    def __repr__(self) -> str:
        return (
            f"<User id={self.id!s} "
            f"email={self.email!r} "
            f"active={self.is_active}>"
        )
